# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: true
sudo: required

env:
  global:
    - NOT_CRAN=true

before_install:
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

r-packages:
  - knitr
  - rmarkdown
  - bodenmiller
